CREATE TABLE todo_3 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT,
    content TEXT,
    is_public INTEGER,
    food_orange INTEGER,
    food_apple INTEGER,
    food_banana INTEGER,
    food_melon INTEGER,
    food_grape INTEGER,
    pub_date1 TEXT,
    pub_date2 TEXT,
    pub_date3 TEXT,
    pub_date4 TEXT,
    pub_date5 TEXT,
    pub_date6 TEXT,
    qty1 INTEGER,
    qty2 INTEGER,
    qty3 INTEGER,
    qty4 INTEGER,
    qty5 INTEGER,
    qty6 INTEGER,
    created_at TEXT
);